### ISSUE TITLE
Error: Cannot find module './debug' when using browserify

### ISSUE THREAD

**Issue by mobidev111** [nmccready/angular-simple-logger#10]
I get the following error when using angular-simple-logger with browserfy: 

Error: Cannot find module './debug' from '/Users/Demo/DemoProject/node_modules/angular-simple-logger/dist'

Changing in package.json the main file to the light version works around this problem:
  "main": "./dist/angular-simple-logger.light.js",

**Comment by nmccready** [comment]
Yeah please look at existing issues #7 , there is also an active PR #8
