### ISSUE TITLE
angular-simple-logger is polluting the global namespace with local variables

### ISSUE THREAD

**Issue by Lavan** [nmccready/angular-simple-logger#14]
While looking at #13 I also noticed that many local variables in this package are accessible globally.

In the following method both key and val become global variables.

```javascript
    _isValidLogObject = function(logObject) {
      var isValid;
      isValid = false;
      if (!logObject) {
        return isValid;
      }
      for (key in _fns) {
        val = _fns[key];
        isValid = (logObject[val] != null) && typeof logObject[val] === 'function';
        if (!isValid) {
          break;
        }
      }
      return isValid;
    };
```

As the default settings for CoffeeScript seems to be to generate local variables (with var statements) and from what I can see you haven't specified any strange options, I have no idea how it ends up like this here.

**Comment by nmccready** [comment]
Which version? The new releases are wrapped in a closure.

**Comment by Lavan** [comment]
The meteor version.

**Comment by nmccready** [comment]
Does meteor use CommonJS, if so I can point it to the index.js version.  Also which release can you make an example showing the global variable problem? I can test against that. Or better yet add specs to test the specific release and check for globals.

**Comment by nmccready** [comment]
So setting bare to false might help. 

https://github.com/nmccready/angular-simple-logger/blob/master/gulp/coffeeOptions.coffee

**Comment by Lavan** [comment]
Apparently I must be seeing things/be too tired. Well, actually I didn't step far enough out of your code to see that the "pollution" actually didn't occur. The calling module ALSO had variables called key and val which caused me into thinking your code was the culprit. Meh, sorry about that.

**Comment by nmccready** [comment]
TY for digging deeper.
