### ISSUE TITLE
Name of dist file should be angular-simple-logger.js 

### ISSUE THREAD

**Issue by r0b-** [nmccready/angular-simple-logger#2]
Right now it's named index.js what doesn't seem right...

Thanks
Rob

**Comment by nmccready** [comment]
Depends on your point of view. From a node / CommonJS standpoint this is normal.

**Comment by r0b-** [comment]
Hmmm, I (have to) use it as a transitive dependency of the leaflet directive in a client app. And it's the only lib of around 20 that is using this naming pattern....

**Comment by nmccready** [comment]
I don't want to argue semantics but I will add the naming you desire and leave the index.js for backwards compat.

**Comment by r0b-** [comment]
Great, thanks a lot!

**Comment by nmccready** [comment]
resolved 5b42df6
