### ISSUE TITLE
declare "require" dependency

### ISSUE THREAD

**Issue by karser** [nmccready/angular-simple-logger#21]
Since 0.1.4 it started to use require but it's not declared in bower.json
https://github.com/nmccready/angular-simple-logger/blob/0.1.4/dist/index.js#L9

**Comment by nmccready** [comment]
How are u pulling it down? Which package manager? I assume bower. Anyway it should be pointing to the browser version which encapsulates the common js via browserify.

**Comment by karser** [comment]
Yes it's bower. I use ionic1.2 + angular-google-maps#2.3.2 which requires this package
```
"angular-simple-logger": ">=0.0.1",
```

**Comment by nmccready** [comment]
Which version is it resolving to?

**Comment by nmccready** [comment]
https://github.com/nmccready/angular-simple-logger/blob/master/bower.json#L5

**Comment by nmccready** [comment]
Anyway if you us main-bower files you can override which fist file it is using.
https://github.com/ck86/main-bower-files

very handy and works out all bower kinks.

**Comment by karser** [comment]
I see. In my index.html was the old index file:
```
<script src="lib/angular-simple-logger/dist/index.js"></script>
```
I'll change it, thanks.
