### ISSUE TITLE
follow typical log-level conventions

### ISSUE THREAD

**Issue by zacronos** [nmccready/angular-simple-logger#3]
See some examples here:
* https://github.com/nlog/nlog/wiki/Log-levels
* http://commons.apache.org/proper/commons-logging/guide.html#Message_PrioritiesLevels
* https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html

`logger.log` should always log, as the name indicates.  `logger.debug` is more detailed / less important than `logger.info`.

**Comment by nmccready** [comment]
Thanks my bad on this.

**Comment by nmccready** [comment]
I will switch the levels to:

```
LEVELS =
    debug: 1
    info: 2
    warn: 3
    error: 4
    log: 5
```

**Comment by nmccready** [comment]
Fixed in https://github.com/nmccready/angular-simple-logger/releases/tag/0.1.0
