### ISSUE TITLE
Cannot find module './debug'

### ISSUE THREAD

**Issue by celsomarques** [nmccready/angular-simple-logger#7]
Hey,

I'm facing an issue here.
`Error: Cannot find module './debug' from '/Users/user/project/ui/node_modules/angular-simple-logger/dist'`

I'm using browserify and this project is only frontend.

Thanks in advance,
Celso

**Comment by nmccready** [comment]
What version is this happening on?

**Comment by celsomarques** [comment]
0.1.1, 0.1.2 and 0.1.3

0.1.0 is ok!

**Comment by nmccready** [comment]
nvm this is happening on latest, as problem is here https://github.com/nmccready/angular-simple-logger/blob/master/dist/angular-simple-logger.js#L353

So I will have to dig into this deeper as this is happening since it is being packed via broswerify. I wrapped visionmedia/debug which supports CommonJS, but I am attempting to make it work in the browser so window.debug is not overwritten. Maybe this is a bad idea. 

Anyway so the require('./debug') error is happening since it is trying to satisfy the visionmedia dependencies. Thing is; it doesn't need to as everything is there that it needs.

**Comment by nmccready** [comment]
I am using browserify as well but I am not packing my vendor dependencies hence why I am not seeing this problem. So for the time being I suggest doing something similar.

**Comment by celsomarques** [comment]
Ok. Thank you!!

**Comment by nmccready** [comment]
Also if you want you can use the light version and you should not have this problem as well. The light version is basically the same as 0.1.0 . So if you can override what browserify uses for angular-simple-logger you can do that.

**Comment by nmccready** [comment]
BTW this is probably gonna take some time as this is a complex issue.

**Comment by nmccready** [comment]
Also note this is a problem for webpack and requirejs users as well.

**Comment by nmccready** [comment]
Possible solutions:
- keep build as is and figure out how to wrap the debug code appropriately to fix the issue
- browserify or webpack this project
-- the reason I didn't do this to begin with was to keep the line numbers down to not have the CommonJS bloat.

**Comment by nmccready** [comment]
Well the less mess and headache so everyone can sleep at night is to browserify. So I can leave the light version as is, or I can browserify it all.

**Comment by nmccready** [comment]
Please test this branch @celsomarques  , I need to know if this works.

**Comment by nmccready** [comment]
Ha well I was wrong originally, browserify is smaller and easier :) cool

**Comment by celsomarques** [comment]
I don't know if I put correctly in my package.json.
Is it correct?

`"angular-simple-logger": "git@github.com:nmccready/angular-simple-logger.git#issue_7/browserify"`

If yes, it doesn't work yet :(

**Comment by nmccready** [comment]
umm that should work, try `rm -rf node_modules/angular-simple-logger` . Also double check the installed file has these [lines](https://github.com/nmccready/angular-simple-logger/blob/issue_7/browserify/dist/index.js#L17).

**Comment by nmccready** [comment]
If it still doesn't then we have a problem we probably need to report to visionmedia/debug itself. It also would be useful to run my specs browserified as well.

**Comment by celsomarques** [comment]
I tried removing the package and installing again but it didn't solve the issue
I found the line you mentioned, but I think problem still happens because of this [line](
https://github.com/nmccready/angular-simple-logger/blob/issue_7/browserify/dist/index.js#L149)

**Comment by nmccready** [comment]
So it seems like we may have to have a separate commonjs file that is not wrapped as that works. This is annoying as I would prefer to only have one build file.

**Comment by nmccready** [comment]
@celsomarques try index.js now

**Comment by nmccready** [comment]
closing due to PR

**Comment by nmccready** [comment]
Re-opening since most people do not search closed issues.

**Comment by celsomarques** [comment]
Hey Nicholas,

I tried index.js but it didn't work standalone.
But as you included `require('debug')` instead of `require('./debug')` I included debug as dependency of my project and it worked perfectly.

Thanks a lot!!!

**Comment by nmccready** [comment]
If you use index.js as a standalone, then all should need to do is `require('angular-simple-logger')` and it should work. You shouldnt need to pull in the dependency explicitly.

**Comment by nmccready** [comment]
This is equivalent to `require('angular-simple-logger')`

**Comment by celsomarques** [comment]
As standalone I mean only require angular-simple-logger as dependency using browserify without any other dependency.
In this case I included debug as dependency and it worked.

**Comment by nmccready** [comment]
If you're using index.js through your app via browserify then all you need is the above require. I think we can close this. After I merge.

**Comment by celsomarques** [comment]
Actually only with require('angular-simple-logger') didn't work. I removed debug from package.json to test it again.

package.json
`"angular-simple-logger": "git@github.com:nmccready/angular-simple-logger.git#issue_7/browserify"`

Running browserify
`Error: Cannot find module 'debug' from '/Users/user/project/ui/node_modules/angular-simple-logger/dist'`

**Comment by nmccready** [comment]
did you rerun npm install prior?

**Comment by nmccready** [comment]
the debug dependency needs to be nested in angular-simple-logger/node_modules

**Comment by nmccready** [comment]
I guess I will make an example using browserify to double check.

**Comment by celsomarques** [comment]
yes I did. :(

**Comment by suprMax** [comment]
can you pleaes simply move "debug" to "dependencies" of package.json? would make life much easier

**Comment by nmccready** [comment]
Yeah no prob, brain fart on that.

**Comment by nmccready** [comment]
@suprMax done, "simply" be kind to others

**Comment by suprMax** [comment]
thanks dude

**Comment by celsomarques** [comment]
0.1.4 worked correctly
Thank you Nicholas :+1:
